### ISSUE TITLE
Engine reconfigure fails after stopping data warehouse service

### ISSUE THREAD

**Issue by axon-obriend** [oVirt/ovirt-dwh#74]
> **IMPORTANT!**: oVirt prior to 4.5 reached end of life.
> If you have an issue on an older version please
> upgrade to latest stable release before opening an issue.

* oVirt Engine: ovirt-engine-4.5.7-0.master.20251029141850.git6e58a03353.el9.noarch

Attempting to run engine-setup to reconfigure the engine -- in this case to initialize the Cinderlib database -- fails  after stopping the ovirt-engine-dwhd service. It erroneously reports that the data warehouse is running.

**To reproduce**
Run
engine-setup --reconfigure-optional-components

**Expected behavior**

Engine correctly detects that data warehouse is stopped

**Screenshots

```
          Configure WebSocket Proxy               : True
         
          Please confirm installation settings (OK, Cancel) [OK]:
[ INFO  ] Cleaning async tasks and compensations
[ INFO  ] Unlocking existing entities
[ INFO  ] Checking the Engine database consistency
[ INFO  ] Stage: Transaction setup
[ INFO  ] Stopping engine service
[ INFO  ] Stopping ovirt-fence-kdump-listener service
[ INFO  ] Stopping dwh service
[ INFO  ] Stopping vmconsole-proxy service
[ INFO  ] Stopping websocket-proxy service
[ INFO  ] Stopping DWH service on host ovirt.cecnet.gmu.edu...
[ ERROR ] ovirt-engine-dwhd is currently running.
         Its hostname is ovirt.cecnet.gmu.edu.
         Please stop it before running Setup.
[ ERROR ] Failed to execute stage 'Transaction setup': ovirt-engine-dwhd is currently running
[ INFO  ] DNF Performing DNF transaction rollback
[ INFO  ] Stage: Clean up
          Log file is located at /var/log/ovirt-engine/setup/ovirt-engine-setup-20251112144252-5spah4.log
[ INFO  ] Generating answer file '/var/lib/ovirt-engine/setup/answers/20251112144619-setup.conf'
[ INFO  ] Stage: Pre-termination
[ INFO  ] Stage: Termination
[ ERROR ] Execution of setup failed
[root@ovirt ~]# systemctl status ovirt-engine-dwhd
○ ovirt-engine-dwhd.service - oVirt Engine Data Warehouse
     Loaded: loaded (/usr/lib/systemd/system/ovirt-engine-dwhd.service; enabled; preset: disabled)
     Active: inactive (dead) since Wed 2025-11-12 14:45:17 EST; 1min 25s ago
   Duration: 3d 3h 24min 58.018s
    Process: 2038 ExecStart=/usr/share/ovirt-engine-dwh/services/ovirt-engine-dwhd/ovirt-engine-dwhd.py --redirect-output --systemd>
   Main PID: 2038 (code=exited, status=0/SUCCESS)
        CPU: 50min 49.673s
```

**Additional context**

I'm standing up a new oVirt cluster (installed 10/31/2025). I'd like to use my existing Ceph cluster for storage and need to initialize the Cinderlib database.

**Comment by afccoder** [comment]
same problem with Version: 4.5.7-0.master.20251104145456.git6ed8392902.el9 (updated from 4.5.5 el8)
we researched the problem a little bit further...
in the engine database the DwhCurrentlyRunning var is set to 1:
`SELECT * FROM dwh_history_timekeeping WHERE var_name = 'DwhCurrentlyRunning';`

if we set this var manually to 0 with:
`UPDATE dwh_history_timekeeping SET var_value = '0' WHERE var_name = 'DwhCurrentlyRunning';`
the "engine-setup" works afterwards..

and then the var changes while starting to 1 again

**Comment by dupondje** [comment]
@afccoder : Afaik what should happen is that the setup sets some variable in the database to make dwh stop itself.
And when DWH stops, it should set DwhCorrentlyRunning to 0.

The question is why that doesn't happen. Perhaps the log of the DWH can help?

**Comment by axon-obriend** [comment]
My cluster is fairly quiet, as I'm still figuring out some of the storage networking. I can provide whatever logs I have if you tell me what you need. Probably these?

```
          Log file is located at /var/log/ovirt-engine/setup/ovirt-engine-setup-20251112144252-5spah4.log
[ INFO  ] Generating answer file '/var/lib/ovirt-engine/setup/answers/20251112144619-setup.conf'
```

**Comment by peter-boden** [comment]
@axon-obriend is it possible to provide:

- The dwh log? It should be inside `/var/log/ovirt-engine-dwh`
- The systemd journal `journalctl -u ovirt-engine-dwhd.service --since "2025-11-12 14:40:00" --until "2025-11-12 14:50:00"`
- The full install log if you still have it: `/var/log/ovirt-engine/setup/ovirt-engine-setup-20251112144252-5spah4.log`
- Maybe the answer file mentioned: `/var/lib/ovirt-engine/setup/answers/20251112144619-setup.conf`

**Comment by dupondje** [comment]
No need for the info anymore. We found the root cause and working on a fix!

**Comment by axon-obriend** [comment]
w00t!

I was starting to pull that together for you. Thanks for your help.

**Comment by dupondje** [comment]
Fixed in https://github.com/oVirt/ovirt-dwh/pull/76

**Comment by axon-obriend** [comment]
Still having this issue. Per [this document](https://www.ovirt.org/documentation/upgrade_guide/#upgrading-self-hosted-engine-environment) I did
`dnf update ovirt\*setup\*`

and then ran 'ovirt-setup' and it failed. I checked /usr/share/ovirt-engine-dwh/services/ovirt-engine-dwhd/ovirt-engine-dwhd.py, and didn't see the new code in the commit, so I upgraded the rest of the ovirt packages with 
`dnf upgrade ovirt\*`

And I was able to see the addition of
`def _executeEngineDbQuery(self, query, params, operation_description):`
in ovirt-engine-dwhd.py

I re-ran ovirt-setup and I'm still getting the error. Attaching logs etc.

[journalctl-dwhd.log](https://github.com/user-attachments/files/23912480/journalctl-dwhd.log)
[ovirt-engine-dwhd.log](https://github.com/user-attachments/files/23912481/ovirt-engine-dwhd.log)
[ovirt-engine-setup-20251203112707-03odnr.log](https://github.com/user-attachments/files/23912482/ovirt-engine-setup-20251203112707-03odnr.log)
[20251203112839-setup.conf.txt](https://github.com/user-attachments/files/23912488/20251203112839-setup.conf.txt)

What's the command/psql query I can use to shut down the data warehouse and get through the setup?

**Comment by peter-boden** [comment]
You can run ([as seen here](https://github.com/oVirt/ovirt-dwh/pull/76/files#diff-1bd3d0f9bf0048fc59f5fb9ee1cc1ebd6a12b6c2d8d00885a306a622390c7ae6R152-R153)):
`UPDATE vdc_options SET option_value = '1' WHERE option_name = 'DisconnectDwh'`

But you need to set it back to 0 before attempting to start dwh again, otherwise it will quit immediately.

Meanwhile, I'll look into why it failed for you.

**Comment by dupondje** [comment]
@axon-obriend : fixed build just published, can you test again? :)

**Comment by axon-obriend** [comment]
I should be able to do this today. Just to be clear: The fix seems to be in 

ovirt-engine-dwh-4.5.10-0.0.master.YYYYMMDDhhmmss.el9.noarch

and I have ovirt-engine-dwh-4.5.10-0.0.master.20251202133620.el9.noarch currently installed, so I need to wait for >20251202133620 (which doesn't seem to have been published or propagated as of the time of this post).

**Comment by dupondje** [comment]
https://copr.fedorainfracloud.org/coprs/ovirt/ovirt-master-snapshot/build/9886642/
The ovirt-engine-dwh package indeed :)

**Comment by afccoder** [comment]
In my case this fixed the bug. Thank you!

**Comment by axon-obriend** [comment]
OK. I updated the packages and ran engine-setup. I was still getting a failure message when I selected "Yes" to the vacuum database questions. I'm running it now taking the default "No" when vacuuming and it seems to be working.

**Comment by axon-obriend** [comment]
Confirming that I got through engine-setup, but only after answering "No" to 

"Perform full vacuum on the oVirt engine history datbase ovirt_engine_history@localhost?"
and
"Perform full vacuum on the engine database engine@localhost?"

Not quite an unqualified success, but I'm over the hump!

**Comment by axon-obriend** [comment]
Also successfully ran

engine-setup --reconfigure-optional-components

Also answering "No" to the vacuum questions.
